configs:
- id: maint-3
  config:
    name: "maintenance 3"
    template: ../maintenance_recurring.json
    parameters:
      maintenance_name: "test maintenance 3 - recurring"
      start_time: "05:00:00"
      end_time: "07:00:00"
      day_of_week: "SUNDAY"
      schedule_start: "2024-01-01"
      schedule_end: "2026-01-01"
  type:
    settings:
      schema: builtin:alerting.maintenance-window
      scope: environment
